### ISSUE TITLE
Add Gujarati stopwords

### ISSUE THREAD

**Issue by bsolomon1124** [stopwords-iso/stopwords-iso#5]
Source:

> https://github.com/quanteda/stopwords/blob/master/data-raw/other/gujarati-stopwords.txt

Original source appears to be:

> https://github.com/gujarati-ir/Gujarati-Stop-Words

This R package in turn also uses this repo.

Glad to open a PR.

**Comment by genediazjr** [comment]
added it. thanks for the contribution!
