### ISSUE TITLE
Greek stopwords are on ancient greek

### ISSUE THREAD

**Issue by nutcracker123** [stopwords-iso/stopwords-iso#7]
Greek stop words are on ancient greek. Not usable i believe

**Comment by nutcracker123** [comment]
This article would help: https://www.translatum.gr/forum/index.php?topic=3550.0
If you need help let me know :)

**Comment by genediazjr** [comment]
sorry for the very late response.  added them [here](https://github.com/stopwords-iso/stopwords-el/commit/1895b60d34111175971cf609b52e3a91e821864c)
